# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-07 12:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='the description of the list', max_length=128)),
                ('archived', models.BooleanField(help_text='whether the list is archived or not')),
                ('user', models.ForeignKey(help_text='the user that owns the list', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='the description of the item', max_length=128)),
                ('checked', models.BooleanField(default=False, help_text='whether the items has been crossed out or not')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='server.ShoppingList')),
            ],
        ),
    ]
