# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-07 14:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='index',
            field=models.IntegerField(default=0, help_text='the place in the list'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='user',
            field=models.ForeignKey(help_text='the user that owns the list', on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
