# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-07 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20171207_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='archived',
            field=models.BooleanField(default=False, help_text='whether the list is archived or not'),
        ),
    ]
