# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-09 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20171207_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
