--transaction 2
USE lab3;

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED				--dirty reads
SET TRANSACTION ISOLATION LEVEL READ COMMITTED					--solution: BLOCARE SHARED PE OPERATIE DE CITIRE

BEGIN TRAN
	SELECT * FROM People WHERE name = 'Geo Gheroghe';
	WAITFOR DELAY '00:00:05';
	SELECT * FROM People WHERE name = 'Geo Gheorghe';			--citesc inainte de terminarea tranzactiei
COMMIT TRAN
GO



SET TRANSACTION ISOLATION LEVEL READ COMMITTED					--non repeatable reads
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ					--solution: BLOCARE SHARED PE TRANZACTIE DE CITIRE

BEGIN TRAN
	SELECT * FROM People
	WAITFOR DELAY '00:00:05'
	SELECT * FROM People										--citesc dupa terminarea tranzactiei
COMMIT TRAN
GO


SET TRANSACTION ISOLATION LEVEL REPEATABLE READ					--phantom reads
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE					--SOLUTION: LOCK KEY RANGE

BEGIN TRAN
	SELECT * FROM People
	WHERE age BETWEEN 50 AND 70
	WAITFOR DELAY '00:00:05'
	SELECT * FROM People
	WHERE age BETWEEN 50 AND 70
COMMIT TRAN
go

SET DEADLOCK_PRIORITY HIGH							
go

CREATE PROCEDURE deadlock1
AS
BEGIN TRAN											--DEADLOCK
	UPDATE Cars SET name = name + 'TR 2' WHERE code = 3
	WAITFOR DELAY '00:00:10'
	UPDATE People SET name = name + 'TR 2' WHERE code = 1
COMMIT TRAN
GO

EXEC deadlock1;